In [3]:
import tensorflow as tf
import numpy as np
ep=np.exp(-10) #a small number
tf.enable_eager_execution()

In [4]:
def soft_max(Qhat): #only takes float type argument
    return tf.nn.softmax(Qhat)

In [5]:
def one_hot_matrix(labels, K):
    """
    Creates a matrix where the i-th row corresponds to the ith dimension and the jth column
                     corresponds to the jth bin. So if dimension i had a label j, then entry (i,j) 
                     will be 1. 
                     
    Arguments:
    labels -- vector containing the bin label from function bin_b
    K -- number of bin
    """
    b = labels.flatten()
    
    # Use tf.one_hot, be careful with the axis
    return tf.one_hot(b,K,axis=1)

In [8]:
def cdf_piecewise_linear(xB,K,Q): #inputs: xB, matrix Q =(dim_xB,K) computed from xA, number of bins K
    #print(xB)
    Q=soft_max(Q) #pdf
    #print(Q)
    dim=np.shape(xB)[0] #get the dimension of xB
    b=np.floor(xB*K) #get the bin number of xB (dim,1)
    #print(b)
    Qindex=np.pad([np.array(range(0,K))],((0,dim-1),(0,0)),"edge") #create a matrix outputting Q's index 
    part=(Qindex<b)*Q #output the part that is inside the sum of Eq(13), (dim,K)
    #print(cdfpart)
    proj=one_hot_matrix(b,K) #create a mask according to label b, (dim,K)
    cdftotal=np.sum(part+Q*proj*(K*xB-b),axis=1,keepdims=True) #output the cdf (dim,1)
    return cdftotal

In [7]:
#test cdf_piecewise_linear(np.ones((3,1)),5,np.random.randint(100,size=(3,5))/70) 

[[1.]
 [1.]
 [1.]]
tf.Tensor(
[[0.12534881 0.14052509 0.22196704 0.2524215  0.25973756]
 [0.15068947 0.20052432 0.18670073 0.17136447 0.29072102]
 [0.09727127 0.27598896 0.10009054 0.30068859 0.22596065]], shape=(3, 5), dtype=float64)
[[5.]
 [5.]
 [5.]]


InternalError: Could not find valid device for node.
Node: {{node OneHot}}
All kernels registered for op OneHot :
  device='XLA_CPU'; TI in [DT_INT32, DT_UINT8, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_GPU'; TI in [DT_INT32, DT_UINT8, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_QINT32, DT_BFLOAT16, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_CPU_JIT'; TI in [DT_INT32, DT_UINT8, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_GPU_JIT'; TI in [DT_INT32, DT_UINT8, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_QINT32, DT_BFLOAT16, DT_HALF, DT_UINT32, DT_UINT64]
  device='CPU'; TI in [DT_INT64]; T in [DT_VARIANT]
  device='CPU'; TI in [DT_INT32]; T in [DT_VARIANT]
  device='CPU'; TI in [DT_UINT8]; T in [DT_VARIANT]
  device='CPU'; TI in [DT_INT64]; T in [DT_RESOURCE]
  device='CPU'; TI in [DT_INT32]; T in [DT_RESOURCE]
  device='CPU'; TI in [DT_UINT8]; T in [DT_RESOURCE]
  device='CPU'; TI in [DT_INT64]; T in [DT_STRING]
  device='CPU'; TI in [DT_INT32]; T in [DT_STRING]
  device='CPU'; TI in [DT_UINT8]; T in [DT_STRING]
  device='CPU'; TI in [DT_INT64]; T in [DT_BOOL]
  device='CPU'; TI in [DT_INT32]; T in [DT_BOOL]
  device='CPU'; TI in [DT_UINT8]; T in [DT_BOOL]
  device='CPU'; TI in [DT_INT64]; T in [DT_COMPLEX128]
  device='CPU'; TI in [DT_INT32]; T in [DT_COMPLEX128]
  device='CPU'; TI in [DT_UINT8]; T in [DT_COMPLEX128]
  device='CPU'; TI in [DT_INT64]; T in [DT_COMPLEX64]
  device='CPU'; TI in [DT_INT32]; T in [DT_COMPLEX64]
  device='CPU'; TI in [DT_UINT8]; T in [DT_COMPLEX64]
  device='CPU'; TI in [DT_INT64]; T in [DT_DOUBLE]
  device='CPU'; TI in [DT_INT32]; T in [DT_DOUBLE]
  device='CPU'; TI in [DT_UINT8]; T in [DT_DOUBLE]
  device='CPU'; TI in [DT_INT64]; T in [DT_FLOAT]
  device='CPU'; TI in [DT_INT32]; T in [DT_FLOAT]
  device='CPU'; TI in [DT_UINT8]; T in [DT_FLOAT]
  device='CPU'; TI in [DT_INT64]; T in [DT_BFLOAT16]
  device='CPU'; TI in [DT_INT32]; T in [DT_BFLOAT16]
  device='CPU'; TI in [DT_UINT8]; T in [DT_BFLOAT16]
  device='CPU'; TI in [DT_INT64]; T in [DT_HALF]
  device='CPU'; TI in [DT_INT32]; T in [DT_HALF]
  device='CPU'; TI in [DT_UINT8]; T in [DT_HALF]
  device='CPU'; TI in [DT_INT64]; T in [DT_INT8]
  device='CPU'; TI in [DT_INT32]; T in [DT_INT8]
  device='CPU'; TI in [DT_UINT8]; T in [DT_INT8]
  device='CPU'; TI in [DT_INT64]; T in [DT_UINT8]
  device='CPU'; TI in [DT_INT32]; T in [DT_UINT8]
  device='CPU'; TI in [DT_UINT8]; T in [DT_UINT8]
  device='CPU'; TI in [DT_INT64]; T in [DT_INT16]
  device='CPU'; TI in [DT_INT32]; T in [DT_INT16]
  device='CPU'; TI in [DT_UINT8]; T in [DT_INT16]
  device='CPU'; TI in [DT_INT64]; T in [DT_UINT16]
  device='CPU'; TI in [DT_INT32]; T in [DT_UINT16]
  device='CPU'; TI in [DT_UINT8]; T in [DT_UINT16]
  device='CPU'; TI in [DT_INT64]; T in [DT_INT32]
  device='CPU'; TI in [DT_INT32]; T in [DT_INT32]
  device='CPU'; TI in [DT_UINT8]; T in [DT_INT32]
  device='CPU'; TI in [DT_INT64]; T in [DT_INT64]
  device='CPU'; TI in [DT_INT32]; T in [DT_INT64]
  device='CPU'; TI in [DT_UINT8]; T in [DT_INT64]
  device='GPU'; TI in [DT_INT64]; T in [DT_INT64]
  device='GPU'; TI in [DT_INT32]; T in [DT_INT64]
  device='GPU'; TI in [DT_UINT8]; T in [DT_INT64]
  device='GPU'; TI in [DT_INT64]; T in [DT_INT32]
  device='GPU'; TI in [DT_INT32]; T in [DT_INT32]
  device='GPU'; TI in [DT_UINT8]; T in [DT_INT32]
  device='GPU'; TI in [DT_INT64]; T in [DT_BOOL]
  device='GPU'; TI in [DT_INT32]; T in [DT_BOOL]
  device='GPU'; TI in [DT_UINT8]; T in [DT_BOOL]
  device='GPU'; TI in [DT_INT64]; T in [DT_DOUBLE]
  device='GPU'; TI in [DT_INT32]; T in [DT_DOUBLE]
  device='GPU'; TI in [DT_UINT8]; T in [DT_DOUBLE]
  device='GPU'; TI in [DT_INT64]; T in [DT_FLOAT]
  device='GPU'; TI in [DT_INT32]; T in [DT_FLOAT]
  device='GPU'; TI in [DT_UINT8]; T in [DT_FLOAT]
  device='GPU'; TI in [DT_INT64]; T in [DT_HALF]
  device='GPU'; TI in [DT_INT32]; T in [DT_HALF]
  device='GPU'; TI in [DT_UINT8]; T in [DT_HALF]
 [Op:OneHot] name: one_hot/

In [9]:
def normalize_V(V,Wn): #inputs: V =(dim_xB,K+1) and W =(dim_xB,K) computed and normalized from xA
    (dim,K)=np.shape(Wn) #get the dimension and number of bins
    expV=np.exp(V) #(dim,K+1)
    Vdeno=np.sum(0.5*(expV[:,0:K]+expV[:,1:K+1])*Wn,axis=1,keepdims=True) #(dim,1)   
    return np.true_divide(expV,Vdeno)

In [10]:
def normalize_W(W):
    return soft_max(W)

In [40]:
def alpha(xB,Wn,b):
    print(b)
    print(Wn[:b])
    return xB-np.cumsum(Wn,axis=1,keepdims=True)[b]/Wn[b]

In [11]:
def bin_b_quad(xB,Wn):
    #print(xB)
    #print(Wn)
    (dim,K)=np.shape(Wn)
    Wcum=np.cumsum(Wn,axis=1) #get the cdf in each dimension of W
    mask=((xB-Wcum)>ep) #to avoid the precision issue, compare to a small number epsilon instead of zero
    Wtrun=mask*Wcum 
    b=np.reshape(np.argmax(Wtrun,axis=1),(dim,1))
    b=b+np.reshape(np.amax(Wtrun,axis=1)>0,(dim,1))*np.ones((dim,1))
    return b

In [41]:
def lerp(xB,Wn,Vn):
    (dim,K)=np.shape(Wn)
    b=bin_b_quad(xB,Wn)
    a=alpha(xB,Wn,b)
    print(a)
    #print(b)
    #print(a)
    proj=one_hot_matrix(b,K) #create a mask according to label b, (dim,K)
    #print(proj)
    diff= np.sum((-Vn[:,0:K]+Vn[:,1:K+1])*proj,axis=1,keepdims=True) #(dim,1)
    #print(diff)
    return a*(diff)+np.sum(Vn[:,0:K]*proj,axis=1,keepdims=True)

In [42]:
def cdf_piecewise_quad(xB,Wn,Vn):
    (dim,K)=np.shape(Wn)
    b=bin_b_quad(xB,Wn)
    #print(b)
    a=alpha(xB,Wn,b)
    #print(a)
    proj=one_hot_matrix(b,K) #create a mask according to label b, (dim,K)
    Wb=np.reshape(np.sum(Wn*proj,axis=1),(dim,1))
    
    Vb=np.sum(Vn[:,0:K]*proj,axis=1,keepdims=True)
    Vbplusone=np.sum(Vn[:,1:K+1]*proj,axis=1,keepdims=True)

    Windex=np.pad([np.array(range(0,K))],((0,dim-1),(0,0)),"edge") #create a matrix outputting W's indices
    part=(Windex<b)*(0.5*(Vn[:,0:K]+Vn[:,1:K+1])*Wn)
    constant=np.sum(part,axis=1,keepdims=True)
    #print(constant)
    
    return (a*a*0.5*(Vbplusone-Vb)+a*Vb)*Wb+constant

In [43]:
xB=np.random.rand(3,1)
#print(xB)
Wn1=normalize_W(np.random.rand(3,5))
#print(Wn1)
Vn1=normalize_V(np.random.rand(3,6),Wn1) #test
#print(Vn1)
cdf_piecewise_quad(xB,Wn1,Vn1)

[[4.]
 [2.]
 [0.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()